import JSZip from "jszip";

export async function downloadProject(req, res) {

    const { files } = req.body;

    const zip = new JSZip();

    const projectFolder = zip.folder("testforge-project");

    files.forEach(file => {
        projectFolder.file(file.filename, file.code);
    });

    // Optional supporting files
    projectFolder.file(
        "README.md",
        `# Generated Automation Project
        
Generated by TestForge AI.

Run instructions will depend on the selected automation tool.`
    );

    projectFolder.file(
        "package.json",
        JSON.stringify({
            name: "testforge-project",
            version: "1.0.0"
        }, null, 2)
    );

    const zipContent = await zip.generateAsync({ type: "nodebuffer" });

    res.set({
        "Content-Type": "application/zip",
        "Content-Disposition": "attachment; filename=testforge-project.zip"
    });

    res.send(zipContent);
}